[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_NETWORK = "testnet"
  NEXT_PUBLIC_HORIZON_URL = "https://horizon-testnet.stellar.org"
  NEXT_PUBLIC_SOROBAN_RPC = "https://soroban-testnet.stellar.org"
  NEXT_PUBLIC_VAULT_TOKEN_CONTRACT_ID = "CAPQ327DH5GR5TGSWPIF44PIIDFQI3TNLA2DSSSY3GTZN32GQC6RNLDS"
  NEXT_PUBLIC_REVENUE_ROUTER_CONTRACT_ID = "CABPHTUFOX6NLNI5TYUSZF2CIXFMSEHGEU364NA4LNQXX5V7ZQDBPH2J"
  NEXT_PUBLIC_SUBSCRIPTION_MANAGER_CONTRACT_ID = "CCMYKDKG5LGUQFJVQFNCWSUVKTKCA33CZ32ZXOLLP6GFM6LUEHNI52F4"
  NEXT_PUBLIC_ADMIN_ADDRESS = "GC5HL2KXTCEXGZU4N6QIDQLIXW6HSFYEZV7ELAEEHDL4EHUMVSTZCPX6"

[[plugins]]
  package = "@netlify/plugin-nextjs"
