[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_NETWORK = "testnet"
  NEXT_PUBLIC_HORIZON_URL = "https://horizon-testnet.stellar.org"
  NEXT_PUBLIC_SOROBAN_RPC = "https://soroban-testnet.stellar.org"
  NEXT_PUBLIC_VAULT_TOKEN_CONTRACT_ID = "CBB3LIJZJ7CSPKVVFHVFQ2E2UPFSVKWSSZI2WC34NTL32UJPCIWZFTWA"
  NEXT_PUBLIC_REVENUE_ROUTER_CONTRACT_ID = "CARIU43DRKA3UZIEVRTRI5GY5QUX2OGIHWCCJ4GKHNNCQO27QPZOFI22"
  NEXT_PUBLIC_SUBSCRIPTION_MANAGER_CONTRACT_ID = "CCWWFT7W3GPFC23QQDWZKTKTACFMBA6ZREIEFRHFIX5EGOX4KZUMCGCZ"
  NEXT_PUBLIC_ADMIN_ADDRESS = "GB7FBPFF4EZ7ZTS4GSODM2RDWHGIRPAK3FGBEEMMGLLEZYFIYBUXYYEI"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
